
# TEST ROUTE
GET http://localhost:3002/api/v1/ HTTP/1.1
Content-Type: application/json

### 

# REGISTER SUCCESS
POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "username": "medic112",
  "email": "medic112@example.com",
  "password": "111111"
}

### 

# REGISTER 422 (all fields required)
POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "username": "",
  "email": "email@example.com",
  "password": "password123"
}

### 

# REGISTER 422 (password length)

POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "username": "username",
  "email": "email@example.com",
  "password": "12345"
}

### 

# LOGIN SUCCESS

POST http://localhost:3002/api/v1/login HTTP/1.1
Content-type: application/json

{
  "username": "medic1111",
  "password": "111111"
}

###

# LOGIN 422 (all fields required)

POST http://localhost:3002/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": "pasword123"
}

###

# RANK SUCCESS 
GET http://localhost:3002/api/v1/rank HTTP/1.1
Content-Type: application/json

###

# ATTACK SUCCESS
PATCH http://localhost:3002/api/v1/users/medic1111/attack/5 HTTP/1.1
Content-Type: application/json

{
  "units": [
  {
        "hero_type": "warrior",
        "attack": 5,
        "available": 4,
        "battling": 1
      },
      {
        "hero_type": "vicking",
        "attack": 10,
        "available": 2,
        "battling": 1
      },
      {
        "hero_type": "magician",
        "attack": 15,
        "available": 2,
        "battling": 1
      },
      {
        "hero_type": "prince",
        "attack": 20,
        "available": 3,
        "battling": 1
      }
    ]
}