
# TEST ROUTE
GET http://localhost:3002/api/v1/ HTTP/1.1
Content-Type: application/json

### 

# REGISTER SUCCESS
POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "username": "medic11",
  "email": "medic11@example.com",
  "password": "111111"
}

### 

# REGISTER 422 (all fields required)
POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "username": "",
  "email": "email@example.com",
  "password": "password123"
}

### 

# REGISTER 422 (password length)

POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "username": "username",
  "email": "email@example.com",
  "password": "12345"
}

### 

# LOGIN SUCCESS

POST http://localhost:3002/api/v1/login HTTP/1.1
Content-type: application/json

{
  "username": "medic1111",
  "password": "111111"
}

###

# LOGIN 422 (all fields required)

POST http://localhost:3002/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": "pasword123"
}